#!/bin/bash

function createcommissioner() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/commissioner.voting.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/commissioner.voting.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-commissioner --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-commissioner.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-commissioner.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-commissioner.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-commissioner.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/commissioner.voting.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy commissioner's CA cert to commissioner's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/commissioner.voting.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem" "${PWD}/organizations/peerOrganizations/commissioner.voting.com/msp/tlscacerts/ca.crt"

  # Copy commissioner's CA cert to commissioner's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/commissioner.voting.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem" "${PWD}/organizations/peerOrganizations/commissioner.voting.com/tlsca/tlsca.commissioner.voting.com-cert.pem"

  # Copy commissioner's CA cert to commissioner's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/commissioner.voting.com/ca"
  cp "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem" "${PWD}/organizations/peerOrganizations/commissioner.voting.com/ca/ca.commissioner.voting.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-commissioner --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-commissioner --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-commissioner --id.name commissioneradmin --id.secret commissioneradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-commissioner -M "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/commissioner.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-commissioner -M "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls" --enrollment.profile tls --csr.hosts peer0.commissioner.voting.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/commissioner.voting.com/peers/peer0.commissioner.voting.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-commissioner -M "${PWD}/organizations/peerOrganizations/commissioner.voting.com/users/User1@commissioner.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/commissioner.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/commissioner.voting.com/users/User1@commissioner.voting.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://commissioneradmin:commissioneradminpw@localhost:7054 --caname ca-commissioner -M "${PWD}/organizations/peerOrganizations/commissioner.voting.com/users/Admin@commissioner.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/commissioner/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/commissioner.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/commissioner.voting.com/users/Admin@commissioner.voting.com/msp/config.yaml"
}

function createvoterregistrationauthority() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/voterRegistrationAuthority.voting.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-voterRegistrationAuthority --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-voterRegistrationAuthority.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-voterRegistrationAuthority.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-voterRegistrationAuthority.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-voterRegistrationAuthority.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy voterRegistrationAuthority's CA cert to voterRegistrationAuthority's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem" "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/msp/tlscacerts/ca.crt"

  # Copy voterRegistrationAuthority's CA cert to voterRegistrationAuthority's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem" "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/tlsca/tlsca.voterRegistrationAuthority.voting.com-cert.pem"

  # Copy voterRegistrationAuthority's CA cert to voterRegistrationAuthority's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/ca"
  cp "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem" "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/ca/ca.voterRegistrationAuthority.voting.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-voterRegistrationAuthority --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-voterRegistrationAuthority --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-voterRegistrationAuthority --id.name candidateadmin --id.secret candidateadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-voterRegistrationAuthority -M "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-voterRegistrationAuthority -M "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls" --enrollment.profile tls --csr.hosts peer0.voterRegistrationAuthority.voting.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/peers/peer0.voterRegistrationAuthority.voting.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-voterRegistrationAuthority -M "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/users/User1@voterRegistrationAuthority.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/users/User1@voterRegistrationAuthority.voting.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://candidateadmin:candidateadminpw@localhost:10054 --caname ca-voterRegistrationAuthority -M "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/users/Admin@voterRegistrationAuthority.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/voterRegistrationAuthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/voterRegistrationAuthority.voting.com/users/Admin@voterRegistrationAuthority.voting.com/msp/config.yaml"
}

function createvotingbooth() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/votingBooth.voting.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/votingBooth.voting.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-votingBooth --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-votingBooth.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-votingBooth.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-votingBooth.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-votingBooth.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy votingBooth's CA cert to votingBooth's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/tlscacerts/ca.crt"

  # Copy votingBooth's CA cert to votingBooth's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/tlsca/tlsca.votingBooth.voting.com-cert.pem"

  # Copy votingBooth's CA cert to votingBooth's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/ca"
  cp "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/ca/ca.votingBooth.voting.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-votingBooth --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-votingBooth --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-votingBooth --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-votingBooth --id.name votersadmin --id.secret votersadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-votingBooth -M "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-votingBooth -M "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls" --enrollment.profile tls --csr.hosts peer0.votingBooth.voting.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer0.votingBooth.voting.com/tls/server.key"

    echo "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-votingBooth -M "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/msp/config.yaml"

  echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-votingBooth -M "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls" --enrollment.profile tls --csr.hosts peer1.votingBooth.voting.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/peers/peer1.votingBooth.voting.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-votingBooth -M "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/users/User1@votingBooth.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/users/User1@votingBooth.voting.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://votersadmin:votersadminpw@localhost:8054 --caname ca-votingBooth -M "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/users/Admin@votingBooth.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/votingBooth/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/votingBooth.voting.com/users/Admin@votingBooth.voting.com/msp/config.yaml"
}

#!/bin/bash

function createauditor() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/auditor.voting.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/auditor.voting.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-auditor --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/auditor.voting.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy auditor's CA cert to auditor's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/auditor.voting.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/auditor.voting.com/msp/tlscacerts/ca.crt"

  # Copy auditor's CA cert to auditor's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/auditor.voting.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/auditor.voting.com/tlsca/tlsca.auditor.voting.com-cert.pem"

  # Copy auditor's CA cert to auditor's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/auditor.voting.com/ca"
  cp "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/auditor.voting.com/ca/ca.auditor.voting.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-auditor --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-auditor --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-auditor --id.name auditoradmin --id.secret auditoradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/auditor.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls" --enrollment.profile tls --csr.hosts peer0.auditor.voting.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/auditor.voting.com/peers/peer0.auditor.voting.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.voting.com/users/User1@auditor.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/auditor.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/auditor.voting.com/users/User1@auditor.voting.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://auditoradmin:auditoradminpw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.voting.com/users/Admin@auditor.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/auditor.voting.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/auditor.voting.com/users/Admin@auditor.voting.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/voting.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/voting.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/voting.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/voting.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/voting.com/msp/tlscacerts/tlsca.voting.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/voting.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/voting.com/tlsca/tlsca.voting.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/voting.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls" --enrollment.profile tls --csr.hosts orderer.voting.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/msp/tlscacerts/tlsca.voting.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/voting.com/users/Admin@voting.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/voting.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/voting.com/users/Admin@voting.com/msp/config.yaml"
}

createcommissioner
createvoterregistrationauthority
createvotingbooth
createauditor
createOrderer